import type { WorkflowTemplate } from "@/components/templates/types"

// 项目管理流程
export const projectManagementTemplate: WorkflowTemplate = {
  id: "project-management",
  name: "项目管理流程",
  description: "完整的项目规划、执行和监控流程",
  category: "管理",
  nodes: [
    {
      id: "start-node",
      type: "start",
      position: { x: 300, y: 50 },
      data: { label: "项目启动" },
    },
    {
      id: "task-project-charter",
      type: "task",
      position: { x: 300, y: 200 },
      data: {
        label: "项目章程",
        description: "制定项目章程和目标",
        properties: {
          负责人: "项目经理",
          内容: "项目目标、范围、利益相关者",
          审批: "项目发起人",
        },
      },
    },
    {
      id: "task-stakeholder-analysis",
      type: "task",
      position: { x: 300, y: 350 },
      data: {
        label: "利益相关者分析",
        description: "识别和分析项目利益相关者",
        properties: {
          负责人: "项目经理",
          输出: "利益相关者登记册",
          方法: "影响力/利益矩阵",
        },
      },
    },
    {
      id: "task-requirements-gathering",
      type: "task",
      position: { x: 300, y: 500 },
      data: {
        label: "需求收集",
        description: "收集和分析项目需求",
        properties: {
          负责人: "业务分析师",
          方法: "访谈、研讨会、问卷",
          输出: "需求文档",
        },
      },
    },
    {
      id: "task-scope-definition",
      type: "task",
      position: { x: 300, y: 650 },
      data: {
        label: "范围定义",
        description: "定义项目范围和可交付成果",
        properties: {
          负责人: "项目经理、业务分析师",
          输出: "范围说明书、WBS",
          审核: "项目发起人、关键利益相关者",
        },
      },
    },
    {
      id: "task-schedule-development",
      type: "task",
      position: { x: 300, y: 800 },
      data: {
        label: "进度计划",
        description: "制定项目进度计划",
        properties: {
          负责人: "项目经理",
          工具: "甘特图、关键路径法",
          输出: "项目进度计划",
        },
      },
    },
    {
      id: "task-resource-planning",
      type: "task",
      position: { x: 300, y: 950 },
      data: {
        label: "资源规划",
        description: "规划项目所需资源",
        properties: {
          负责人: "项目经理、资源经理",
          内容: "人力资源、设备、材料",
          输出: "资源管理计划",
        },
      },
    },
    {
      id: "task-budget-planning",
      type: "task",
      position: { x: 300, y: 1100 },
      data: {
        label: "预算规划",
        description: "制定项目预算",
        properties: {
          负责人: "项目经理、财务",
          方法: "自下而上估算、类比估算",
          输出: "项目预算",
        },
      },
    },
    {
      id: "task-risk-management",
      type: "task",
      position: { x: 300, y: 1250 },
      data: {
        label: "风险管理",
        description: "识别和规划风险应对",
        properties: {
          负责人: "项目经理、风险专员",
          内容: "风险识别、分析、应对策略",
          输出: "风险登记册",
        },
      },
    },
    {
      id: "task-quality-planning",
      type: "task",
      position: { x: 300, y: 1400 },
      data: {
        label: "质量规划",
        description: "制定质量管理计划",
        properties: {
          负责人: "质量经理",
          内容: "质量标准、保证措施、控制方法",
          输出: "质量管理计划",
        },
      },
    },
    {
      id: "task-communication-planning",
      type: "task",
      position: { x: 300, y: 1550 },
      data: {
        label: "沟通规划",
        description: "制定项目沟通计划",
        properties: {
          负责人: "项目经理",
          内容: "沟通方式、频率、受众",
          输出: "沟通管理计划",
        },
      },
    },
    {
      id: "condition-plan-approval",
      type: "condition",
      position: { x: 300, y: 1700 },
      data: {
        label: "计划审批",
        description: "项目计划审批",
        properties: {
          审批人: "项目发起人、指导委员会",
          标准: "完整性、可行性、资源可用性",
        },
      },
    },
    {
      id: "task-plan-revision",
      type: "task",
      position: { x: 500, y: 1850 },
      data: {
        label: "计划修订",
        description: "根据反馈修订项目计划",
        properties: {
          负责人: "项目经理",
          内容: "调整范围、进度、预算",
          时限: "5个工作日",
        },
      },
    },
    {
      id: "task-team-formation",
      type: "task",
      position: { x: 100, y: 1850 },
      data: {
        label: "团队组建",
        description: "组建项目团队",
        properties: {
          负责人: "项目经理、人力资源",
          内容: "团队招募、角色分配",
          输出: "项目团队名册",
        },
      },
    },
    {
      id: "task-kickoff-meeting",
      type: "task",
      position: { x: 100, y: 2000 },
      data: {
        label: "启动会议",
        description: "召开项目启动会议",
        properties: {
          负责人: "项目经理",
          参与者: "项目团队、关键利益相关者",
          内容: "项目目标、角色责任、时间表",
        },
      },
    },
    {
      id: "task-execution",
      type: "task",
      position: { x: 100, y: 2150 },
      data: {
        label: "项目执行",
        description: "执行项目计划",
        properties: {
          负责人: "项目团队",
          内容: "任务分配、工作执行、协调",
          工具: "项目管理软件",
        },
      },
    },
    {
      id: "task-monitoring-control",
      type: "task",
      position: { x: 100, y: 2300 },
      data: {
        label: "监控与控制",
        description: "监控项目进度和绩效",
        properties: {
          负责人: "项目经理",
          内容: "进度跟踪、成本控制、质量监控",
          频率: "每周更新",
        },
      },
    },
    {
      id: "condition-change-request",
      type: "condition",
      position: { x: 100, y: 2450 },
      data: {
        label: "变更请求",
        description: "处理项目变更请求",
        properties: {
          评估人: "变更控制委员会",
          标准: "影响分析、必要性",
        },
      },
    },
    {
      id: "task-change-implementation",
      type: "task",
      position: { x: 250, y: 2600 },
      data: {
        label: "实施变更",
        description: "实施批准的变更",
        properties: {
          负责人: "项目团队",
          内容: "更新计划、通知相关方",
          记录: "变更日志",
        },
      },
    },
    {
      id: "task-status-reporting",
      type: "task",
      position: { x: 100, y: 2750 },
      data: {
        label: "状态报告",
        description: "编制项目状态报告",
        properties: {
          负责人: "项目经理",
          内容: "进度、成本、风险、问题",
          频率: "每周/每月",
        },
      },
    },
    {
      id: "task-deliverable-acceptance",
      type: "task",
      position: { x: 100, y: 2900 },
      data: {
        label: "交付物验收",
        description: "验收项目交付物",
        properties: {
          负责人: "项目经理、客户",
          标准: "验收标准、质量要求",
          输出: "验收文档",
        },
      },
    },
    {
      id: "task-project-closure",
      type: "task",
      position: { x: 100, y: 3050 },
      data: {
        label: "项目收尾",
        description: "完成项目收尾工作",
        properties: {
          负责人: "项目经理",
          内容: "文档归档、资源释放、经验教训",
          输出: "项目总结报告",
        },
      },
    },
    {
      id: "end-node",
      type: "end",
      position: { x: 100, y: 3200 },
      data: { label: "项目完成" },
    },
  ],
  edges: [
    { id: "e1", source: "start-node", target: "task-project-charter", animated: true, type: "default" },
    { id: "e2", source: "task-project-charter", target: "task-stakeholder-analysis", animated: true, type: "default" },
    {
      id: "e3",
      source: "task-stakeholder-analysis",
      target: "task-requirements-gathering",
      animated: true,
      type: "default",
    },
    {
      id: "e4",
      source: "task-requirements-gathering",
      target: "task-scope-definition",
      animated: true,
      type: "default",
    },
    { id: "e5", source: "task-scope-definition", target: "task-schedule-development", animated: true, type: "default" },
    {
      id: "e6",
      source: "task-schedule-development",
      target: "task-resource-planning",
      animated: true,
      type: "default",
    },
    { id: "e7", source: "task-resource-planning", target: "task-budget-planning", animated: true, type: "default" },
    { id: "e8", source: "task-budget-planning", target: "task-risk-management", animated: true, type: "default" },
    { id: "e9", source: "task-risk-management", target: "task-quality-planning", animated: true, type: "default" },
    {
      id: "e10",
      source: "task-quality-planning",
      target: "task-communication-planning",
      animated: true,
      type: "default",
    },
    {
      id: "e11",
      source: "task-communication-planning",
      target: "condition-plan-approval",
      animated: true,
      type: "default",
    },
    {
      id: "e12",
      source: "condition-plan-approval",
      target: "task-team-formation",
      sourceHandle: "a",
      animated: true,
      type: "default",
      label: "通过",
    },
    {
      id: "e13",
      source: "condition-plan-approval",
      target: "task-plan-revision",
      sourceHandle: "b",
      animated: true,
      type: "default",
      label: "需修改",
    },
    { id: "e14", source: "task-plan-revision", target: "condition-plan-approval", animated: true, type: "default" },
    { id: "e15", source: "task-team-formation", target: "task-kickoff-meeting", animated: true, type: "default" },
    { id: "e16", source: "task-kickoff-meeting", target: "task-execution", animated: true, type: "default" },
    { id: "e17", source: "task-execution", target: "task-monitoring-control", animated: true, type: "default" },
    {
      id: "e18",
      source: "task-monitoring-control",
      target: "condition-change-request",
      animated: true,
      type: "default",
    },
    {
      id: "e19",
      source: "condition-change-request",
      target: "task-status-reporting",
      sourceHandle: "a",
      animated: true,
      type: "default",
      label: "无变更",
    },
    {
      id: "e20",
      source: "condition-change-request",
      target: "task-change-implementation",
      sourceHandle: "b",
      animated: true,
      type: "default",
      label: "有变更",
    },
    {
      id: "e21",
      source: "task-change-implementation",
      target: "task-monitoring-control",
      animated: true,
      type: "default",
    },
    {
      id: "e22",
      source: "task-status-reporting",
      target: "task-deliverable-acceptance",
      animated: true,
      type: "default",
    },
    {
      id: "e23",
      source: "task-deliverable-acceptance",
      target: "task-project-closure",
      animated: true,
      type: "default",
    },
    { id: "e24", source: "task-project-closure", target: "end-node", animated: true, type: "default" },
  ],
}

// 人力资源管理流程
export const hrManagementTemplate: WorkflowTemplate = {
  id: "hr-management",
  name: "人力资源管理流程",
  description: "员工招聘、培训、绩效管理的完整流程",
  category: "管理",
  nodes: [
    {
      id: "start-node",
      type: "start",
      position: { x: 300, y: 50 },
      data: { label: "开始HR流程" },
    },
    {
      id: "task-workforce-planning",
      type: "task",
      position: { x: 300, y: 200 },
      data: {
        label: "人力规划",
        description: "规划组织人力需求",
        properties: {
          负责人: "HR总监",
          内容: "人员需求预测、组织结构规划",
          周期: "年度规划",
        },
      },
    },
    {
      id: "task-job-analysis",
      type: "task",
      position: { x: 300, y: 350 },
      data: {
        label: "岗位分析",
        description: "分析岗位职责和要求",
        properties: {
          负责人: "HR经理",
          输出: "岗位说明书、任职资格",
          方法: "访谈、问卷、观察",
        },
      },
    },
    {
      id: "task-recruitment-planning",
      type: "task",
      position: { x: 300, y: 500 },
      data: {
        label: "招聘计划",
        description: "制定招聘策略和计划",
        properties: {
          负责人: "招聘经理",
          内容: "招聘渠道、时间表、预算",
          审批: "HR总监、部门负责人",
        },
      },
    },
    {
      id: "task-job-posting",
      type: "task",
      position: { x: 300, y: 650 },
      data: {
        label: "职位发布",
        description: "在各渠道发布职位信息",
        properties: {
          负责人: "招聘专员",
          渠道: "招聘网站、社交媒体、校园招聘",
          内容: "职位描述、要求、福利",
        },
      },
    },
    {
      id: "task-resume-screening",
      type: "task",
      position: { x: 300, y: 800 },
      data: {
        label: "简历筛选",
        description: "筛选应聘者简历",
        properties: {
          负责人: "招聘专员",
          标准: "教育背景、工作经验、技能匹配度",
          工具: "ATS系统、筛选表",
        },
      },
    },
    {
      id: "task-initial-interview",
      type: "task",
      position: { x: 300, y: 950 },
      data: {
        label: "初试",
        description: "进行初步面试",
        properties: {
          负责人: "HR面试官",
          内容: "基本情况、职业规划、软技能",
          方式: "电话/视频/现场",
        },
      },
    },
    {
      id: "condition-initial-result",
      type: "condition",
      position: { x: 300, y: 1100 },
      data: {
        label: "初试结果",
        description: "评估初试结果",
        properties: {
          评估人: "HR面试官",
          标准: "沟通能力、文化匹配度",
        },
      },
    },
    {
      id: "task-technical-interview",
      type: "task",
      position: { x: 100, y: 1250 },
      data: {
        label: "专业面试",
        description: "进行专业技能面试",
        properties: {
          负责人: "部门经理、技术专家",
          内容: "专业知识、技能测试、案例分析",
          方式: "现场/远程面试",
        },
      },
    },
    {
      id: "task-rejection-notification",
      type: "task",
      position: { x: 500, y: 1250 },
      data: {
        label: "拒绝通知",
        description: "通知未通过的候选人",
        properties: {
          负责人: "招聘专员",
          方式: "邮件/电话",
          内容: "感谢信、建议反馈",
        },
      },
    },
    {
      id: "condition-technical-result",
      type: "condition",
      position: { x: 100, y: 1400 },
      data: {
        label: "专业面试结果",
        description: "评估专业面试结果",
        properties: {
          评估人: "部门经理",
          标准: "专业能力、解决问题能力",
        },
      },
    },
    {
      id: "task-final-interview",
      type: "task",
      position: { x: 100, y: 1550 },
      data: {
        label: "终面",
        description: "进行最终面试",
        properties: {
          负责人: "高级管理层",
          内容: "综合评估、价值观匹配",
          方式: "现场面试",
        },
      },
    },
    {
      id: "condition-final-result",
      type: "condition",
      position: { x: 100, y: 1700 },
      data: {
        label: "终面结果",
        description: "评估终面结果",
        properties: {
          评估人: "高级管理层",
          标准: "综合素质、发展潜力",
        },
      },
    },
    {
      id: "task-offer-preparation",
      type: "task",
      position: { x: 100, y: 1850 },
      data: {
        label: "Offer准备",
        description: "准备录用通知书",
        properties: {
          负责人: "HR经理",
          内容: "薪资福利、入职日期、工作条件",
          审批: "部门负责人、HR总监",
        },
      },
    },
    {
      id: "task-background-check",
      type: "task",
      position: { x: 100, y: 2000 },
      data: {
        label: "背景调查",
        description: "进行背景调查",
        properties: {
          负责人: "HR专员",
          内容: "学历验证、工作经历、犯罪记录",
          方式: "第三方调查、电话核实",
        },
      },
    },
    {
      id: "condition-background-result",
      type: "condition",
      position: { x: 100, y: 2150 },
      data: {
        label: "背景调查结果",
        description: "评估背景调查结果",
        properties: {
          评估人: "HR经理",
          标准: "信息真实性、风险评估",
        },
      },
    },
    {
      id: "task-offer-issuance",
      type: "task",
      position: { x: 100, y: 2300 },
      data: {
        label: "发放Offer",
        description: "向候选人发放Offer",
        properties: {
          负责人: "HR专员",
          方式: "邮件/电话/面谈",
          内容: "正式录用通知书、入职须知",
        },
      },
    },
    {
      id: "condition-offer-acceptance",
      type: "condition",
      position: { x: 100, y: 2450 },
      data: {
        label: "Offer接受",
        description: "候选人是否接受Offer",
        properties: {
          跟进人: "HR专员",
          时限: "一周内",
        },
      },
    },
    {
      id: "task-onboarding-preparation",
      type: "task",
      position: { x: 100, y: 2600 },
      data: {
        label: "入职准备",
        description: "准备新员工入职",
        properties: {
          负责人: "HR专员、行政",
          内容: "工位准备、设备配置、入职材料",
          时间: "入职前一周",
        },
      },
    },
    {
      id: "task-onboarding",
      type: "task",
      position: { x: 100, y: 2750 },
      data: {
        label: "入职培训",
        description: "进行新员工入职培训",
        properties: {
          负责人: "HR培训师、部门导师",
          内容: "公司介绍、制度培训、岗位培训",
          周期: "1-2周",
        },
      },
    },
    {
      id: "task-probation-management",
      type: "task",
      position: { x: 100, y: 2900 },
      data: {
        label: "试用期管理",
        description: "管理员工试用期",
        properties: {
          负责人: "直属经理、HR",
          内容: "目标设定、定期反馈、评估",
          周期: "1-6个月",
        },
      },
    },
    {
      id: "condition-probation-result",
      type: "condition",
      position: { x: 100, y: 3050 },
      data: {
        label: "试用期评估",
        description: "评估试用期表现",
        properties: {
          评估人: "直属经理",
          标准: "工作表现、团队融入度",
        },
      },
    },
    {
      id: "task-formal-employment",
      type: "task",
      position: { x: 100, y: 3200 },
      data: {
        label: "转正",
        description: "办理员工转正",
        properties: {
          负责人: "HR专员",
          内容: "转正评估、薪资调整、档案更新",
          流程: "转正申请、审批、通知",
        },
      },
    },
    {
      id: "end-node",
      type: "end",
      position: { x: 100, y: 3350 },
      data: { label: "招聘流程完成" },
    },
  ],
  edges: [
    { id: "e1", source: "start-node", target: "task-workforce-planning", animated: true, type: "default" },
    { id: "e2", source: "task-workforce-planning", target: "task-job-analysis", animated: true, type: "default" },
    { id: "e3", source: "task-job-analysis", target: "task-recruitment-planning", animated: true, type: "default" },
    { id: "e4", source: "task-recruitment-planning", target: "task-job-posting", animated: true, type: "default" },
    { id: "e5", source: "task-job-posting", target: "task-resume-screening", animated: true, type: "default" },
    { id: "e6", source: "task-resume-screening", target: "task-initial-interview", animated: true, type: "default" },
    { id: "e7", source: "task-initial-interview", target: "condition-initial-result", animated: true, type: "default" },
    {
      id: "e8",
      source: "condition-initial-result",
      target: "task-technical-interview",
      sourceHandle: "a",
      animated: true,
      type: "default",
      label: "通过",
    },
    {
      id: "e9",
      source: "condition-initial-result",
      target: "task-rejection-notification",
      sourceHandle: "b",
      animated: true,
      type: "default",
      label: "不通过",
    },
    {
      id: "e10",
      source: "task-technical-interview",
      target: "condition-technical-result",
      animated: true,
      type: "default",
    },
    {
      id: "e11",
      source: "condition-technical-result",
      target: "task-final-interview",
      sourceHandle: "a",
      animated: true,
      type: "default",
      label: "通过",
    },
    {
      id: "e12",
      source: "condition-technical-result",
      target: "task-rejection-notification",
      sourceHandle: "b",
      animated: true,
      type: "default",
      label: "不通过",
    },
    { id: "e13", source: "task-final-interview", target: "condition-final-result", animated: true, type: "default" },
    {
      id: "e14",
      source: "condition-final-result",
      target: "task-offer-preparation",
      sourceHandle: "a",
      animated: true,
      type: "default",
      label: "通过",
    },
    {
      id: "e15",
      source: "condition-final-result",
      target: "task-rejection-notification",
      sourceHandle: "b",
      animated: true,
      type: "default",
      label: "不通过",
    },
    { id: "e16", source: "task-offer-preparation", target: "task-background-check", animated: true, type: "default" },
    {
      id: "e17",
      source: "task-background-check",
      target: "condition-background-result",
      animated: true,
      type: "default",
    },
    {
      id: "e18",
      source: "condition-background-result",
      target: "task-offer-issuance",
      sourceHandle: "a",
      animated: true,
      type: "default",
      label: "通过",
    },
    {
      id: "e19",
      source: "condition-background-result",
      target: "task-rejection-notification",
      sourceHandle: "b",
      animated: true,
      type: "default",
      label: "不通过",
    },
    { id: "e20", source: "task-offer-issuance", target: "condition-offer-acceptance", animated: true, type: "default" },
    {
      id: "e21",
      source: "condition-offer-acceptance",
      target: "task-onboarding-preparation",
      sourceHandle: "a",
      animated: true,
      type: "default",
      label: "接受",
    },
    { id: "e22", source: "task-onboarding-preparation", target: "task-onboarding", animated: true, type: "default" },
    { id: "e23", source: "task-onboarding", target: "task-probation-management", animated: true, type: "default" },
    {
      id: "e24",
      source: "task-probation-management",
      target: "condition-probation-result",
      animated: true,
      type: "default",
    },
    {
      id: "e25",
      source: "condition-probation-result",
      target: "task-formal-employment",
      sourceHandle: "a",
      animated: true,
      type: "default",
      label: "通过",
    },
    { id: "e26", source: "task-formal-employment", target: "end-node", animated: true, type: "default" },
  ],
}

// 风险管理流程
export const riskManagementTemplate: WorkflowTemplate = {
  id: "risk-management",
  name: "风险管理流程",
  description: "企业风险识别、评估和应对的完整流程",
  category: "管理",
  nodes: [
    {
      id: "start-node",
      type: "start",
      position: { x: 300, y: 50 },
      data: { label: "开始风险管理" },
    },
    {
      id: "task-risk-policy",
      type: "task",
      position: { x: 300, y: 200 },
      data: {
        label: "风险政策制定",
        description: "制定组织风险管理政策",
        properties: {
          负责人: "风险管理委员会",
          内容: "风险偏好、容忍度、管理框架",
          审批: "董事会",
        },
      },
    },
    {
      id: "task-context-establishment",
      type: "task",
      position: { x: 300, y: 350 },
      data: {
        label: "环境建立",
        description: "建立风险管理环境",
        properties: {
          负责人: "风险经理",
          内容: "内外部环境分析、范围确定",
          输出: "风险管理计划",
        },
      },
    },
    {
      id: "task-risk-identification",
      type: "task",
      position: { x: 300, y: 500 },
      data: {
        label: "风险识别",
        description: "识别潜在风险",
        properties: {
          负责人: "风险团队、业务部门",
          方法: "头脑风暴、访谈、核对表",
          输出: "风险清单",
        },
      },
    },
    {
      id: "task-risk-analysis",
      type: "task",
      position: { x: 300, y: 650 },
      data: {
        label: "风险分析",
        description: "分析风险概率和影响",
        properties: {
          负责人: "风险分析师",
          方法: "定性分析、定量分析",
          输出: "风险评估报告",
        },
      },
    },
    {
      id: "task-risk-evaluation",
      type: "task",
      position: { x: 300, y: 800 },
      data: {
        label: "风险评估",
        description: "评估风险等级和优先级",
        properties: {
          负责人: "风险经理",
          标准: "风险矩阵、风险评分",
          输出: "风险优先级列表",
        },
      },
    },
    {
      id: "condition-risk-level",
      type: "condition",
      position: { x: 300, y: 950 },
      data: {
        label: "风险等级判断",
        description: "判断风险等级",
        properties: {
          评估人: "风险委员会",
          标准: "风险评分标准",
        },
      },
    },
    {
      id: "task-high-risk-treatment",
      type: "task",
      position: { x: 100, y: 1100 },
      data: {
        label: "高风险应对",
        description: "制定高风险应对策略",
        properties: {
          负责人: "高级管理层、风险经理",
          策略: "规避、转移、减轻",
          输出: "详细应对计划",
        },
      },
    },
    {
      id: "task-medium-risk-treatment",
      type: "task",
      position: { x: 300, y: 1100 },
      data: {
        label: "中风险应对",
        description: "制定中风险应对策略",
        properties: {
          负责人: "部门经理、风险专员",
          策略: "减轻、分担",
          输出: "应对措施",
        },
      },
    },
    {
      id: "task-low-risk-treatment",
      type: "task",
      position: { x: 500, y: 1100 },
      data: {
        label: "低风险应对",
        description: "制定低风险应对策略",
        properties: {
          负责人: "风险专员",
          策略: "接受、监控",
          输出: "监控计划",
        },
      },
    },
    {
      id: "task-response-planning",
      type: "task",
      position: { x: 300, y: 1250 },
      data: {
        label: "应对计划制定",
        description: "制定详细风险应对计划",
        properties: {
          负责人: "风险经理、业务部门",
          内容: "应对措施、责任人、时间表、资源",
          审批: "风险委员会",
        },
      },
    },
    {
      id: "task-implementation",
      type: "task",
      position: { x: 300, y: 1400 },
      data: {
        label: "计划实施",
        description: "实施风险应对计划",
        properties: {
          负责人: "业务部门、风险专员",
          内容: "执行应对措施、资源分配",
          跟踪: "实施进度跟踪",
        },
      },
    },
    {
      id: "task-monitoring",
      type: "task",
      position: { x: 300, y: 1550 },
      data: {
        label: "风险监控",
        description: "持续监控风险状态",
        properties: {
          负责人: "风险监控团队",
          方法: "关键风险指标、预警系统",
          频率: "定期监控",
        },
      },
    },
    {
      id: "condition-risk-change",
      type: "condition",
      position: { x: 300, y: 1700 },
      data: {
        label: "风险变化",
        description: "评估风险状态是否变化",
        properties: {
          评估人: "风险专员",
          标准: "风险指标变化",
        },
      },
    },
    {
      id: "task-plan-adjustment",
      type: "task",
      position: { x: 500, y: 1850 },
      data: {
        label: "计划调整",
        description: "调整风险应对计划",
        properties: {
          负责人: "风险经理",
          内容: "更新应对措施、资源调整",
          审批: "风险委员会",
        },
      },
    },
    {
      id: "task-reporting",
      type: "task",
      position: { x: 300, y: 2000 },
      data: {
        label: "风险报告",
        description: "编制风险管理报告",
        properties: {
          负责人: "风险经理",
          内容: "风险状态、应对效果、新兴风险",
          频率: "月度/季度报告",
        },
      },
    },
    {
      id: "task-review",
      type: "task",
      position: { x: 300, y: 2150 },
      data: {
        label: "风险管理评审",
        description: "评审风险管理流程有效性",
        properties: {
          负责人: "风险委员会、内审",
          内容: "流程评估、改进建议",
          周期: "年度评审",
        },
      },
    },
    {
      id: "task-improvement",
      type: "task",
      position: { x: 300, y: 2300 },
      data: {
        label: "持续改进",
        description: "改进风险管理流程",
        properties: {
          负责人: "风险管理团队",
          内容: "流程优化、工具更新、培训",
          依据: "评审结果、最佳实践",
        },
      },
    },
    {
      id: "end-node",
      type: "end",
      position: { x: 300, y: 2450 },
      data: { label: "风险管理循环" },
    },
  ],
  edges: [
    { id: "e1", source: "start-node", target: "task-risk-policy", animated: true, type: "default" },
    { id: "e2", source: "task-risk-policy", target: "task-context-establishment", animated: true, type: "default" },
    {
      id: "e3",
      source: "task-context-establishment",
      target: "task-risk-identification",
      animated: true,
      type: "default",
    },
    { id: "e4", source: "task-risk-identification", target: "task-risk-analysis", animated: true, type: "default" },
    { id: "e5", source: "task-risk-analysis", target: "task-risk-evaluation", animated: true, type: "default" },
    { id: "e6", source: "task-risk-evaluation", target: "condition-risk-level", animated: true, type: "default" },
    {
      id: "e7",
      source: "condition-risk-level",
      target: "task-high-risk-treatment",
      sourceHandle: "a",
      animated: true,
      type: "default",
      label: "高风险",
    },
    {
      id: "e8",
      source: "condition-risk-level",
      target: "task-medium-risk-treatment",
      sourceHandle: "a",
      animated: true,
      type: "default",
      label: "中风险",
    },
    {
      id: "e9",
      source: "condition-risk-level",
      target: "task-low-risk-treatment",
      sourceHandle: "b",
      animated: true,
      type: "default",
      label: "低风险",
    },
    {
      id: "e10",
      source: "task-high-risk-treatment",
      target: "task-response-planning",
      animated: true,
      type: "default",
    },
    {
      id: "e11",
      source: "task-medium-risk-treatment",
      target: "task-response-planning",
      animated: true,
      type: "default",
    },
    { id: "e12", source: "task-low-risk-treatment", target: "task-response-planning", animated: true, type: "default" },
    { id: "e13", source: "task-response-planning", target: "task-implementation", animated: true, type: "default" },
    { id: "e14", source: "task-implementation", target: "task-monitoring", animated: true, type: "default" },
    { id: "e15", source: "task-monitoring", target: "condition-risk-change", animated: true, type: "default" },
    {
      id: "e16",
      source: "condition-risk-change",
      target: "task-reporting",
      sourceHandle: "a",
      animated: true,
      type: "default",
      label: "无显著变化",
    },
    {
      id: "e17",
      source: "condition-risk-change",
      target: "task-plan-adjustment",
      sourceHandle: "b",
      animated: true,
      type: "default",
      label: "风险变化",
    },
    { id: "e18", source: "task-plan-adjustment", target: "task-implementation", animated: true, type: "default" },
    { id: "e19", source: "task-reporting", target: "task-review", animated: true, type: "default" },
    { id: "e20", source: "task-review", target: "task-improvement", animated: true, type: "default" },
    { id: "e21", source: "task-improvement", target: "end-node", animated: true, type: "default" },
  ],
}
